# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Vivado_Projects/AXI_COLIB/AXI_COLIB.srcs/sources_1/bd/design_1/ip/design_1_adc_lite_0_2/design_1_adc_lite_0_2.xci
# IP: The module: 'design_1_adc_lite_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Vivado_Projects/AXI_COLIB/AXI_COLIB.gen/sources_1/bd/design_1/ip/design_1_adc_lite_0_2/src/ila_adc_1/ila_adc.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ila_adc || ORIG_REF_NAME==ila_adc} -quiet] -quiet

# XDC: c:/Vivado_Projects/AXI_COLIB/AXI_COLIB.gen/sources_1/bd/design_1/ip/design_1_adc_lite_0_2/src/ila_adc_1/ila_v6_2/constraints/ila.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila_adc || ORIG_REF_NAME==ila_adc} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Vivado_Projects/AXI_COLIB/AXI_COLIB.gen/sources_1/bd/design_1/ip/design_1_adc_lite_0_2/src/ila_adc_1/ila_adc_ooc.xdc

# IP: C:/Vivado_Projects/AXI_COLIB/AXI_COLIB.srcs/sources_1/bd/design_1/ip/design_1_adc_lite_0_2/design_1_adc_lite_0_2.xci
# IP: The module: 'design_1_adc_lite_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Vivado_Projects/AXI_COLIB/AXI_COLIB.gen/sources_1/bd/design_1/ip/design_1_adc_lite_0_2/src/ila_adc_1/ila_adc.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ila_adc || ORIG_REF_NAME==ila_adc} -quiet] -quiet

# XDC: c:/Vivado_Projects/AXI_COLIB/AXI_COLIB.gen/sources_1/bd/design_1/ip/design_1_adc_lite_0_2/src/ila_adc_1/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila_adc || ORIG_REF_NAME==ila_adc} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Vivado_Projects/AXI_COLIB/AXI_COLIB.gen/sources_1/bd/design_1/ip/design_1_adc_lite_0_2/src/ila_adc_1/ila_adc_ooc.xdc
